# Generated by Django 6.0.3 on 2026-04-14 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registration_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationfield',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Campo iscrizione', 'verbose_name_plural': 'Campi iscrizione'},
        ),
        migrations.AlterField(
            model_name='event',
            name='max_registrations',
            field=models.PositiveIntegerField(blank=True, help_text='Lascia vuoto per illimitato', null=True, verbose_name='Posti massimi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Lascia vuoto per nessuna scadenza', null=True, verbose_name='Scadenza iscrizioni'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_notes',
            field=models.TextField(blank=True, help_text='Testo mostrato sopra il form', verbose_name='Note per gli iscritti'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = gratuito', max_digits=8, verbose_name='Quota iscrizione (EUR)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Importo pagato (EUR)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrationfield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrationfield',
            name='options',
            field=models.TextField(blank=True, help_text='Solo per select/radio: una voce per riga', verbose_name='Opzioni'),
        ),
    ]
