# Generated by Django 6.0.3 on 2026-04-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_registrationfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Pubblicato'),
        ),
    ]
