# Generated by Django 6.0.3 on 2026-08-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('free', 'Gratuito'), ('pending', 'In attesa di pagamento'), ('review', 'In verifica PayPal'), ('completed', 'Pagamento completato'), ('failed', 'Pagamento fallito'), ('cancelled', 'Annullato')], default='free', max_length=20, verbose_name='Stato pagamento'),
        ),
    ]
