# Generated by Django 6.0.3 on 2026-04-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('logo', models.ImageField(upload_to='sponsors/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Sito web')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordine')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsor',
                'ordering': ['order', 'name'],
            },
        ),
    ]
