# Generated by Django 5.2.13 on 2026-04-13 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('category', models.CharField(choices=[('regolamento', 'Regolamenti'), ('etico', 'Codice Etico & Carta Etica'), ('safeguarding', 'Safeguarding'), ('privacy', 'Privacy & GDPR'), ('promo', 'Materiale promozionale')], max_length=30, verbose_name='Categoria')),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='File')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordine')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
