"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

try:
    from decouple import config as env_config
except ImportError:
    env_config = None


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env(name, default=''):
    if env_config:
        return env_config(name, default=default)
    if name in os.environ:
        return os.environ[name]

    env_path = BASE_DIR / '.env'
    if env_path.exists():
        for line in env_path.read_text(encoding='utf-8').splitlines():
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            if key.strip() == name:
                return value.strip().strip('"').strip("'")

    return default


def env_bool(name, default=False):
    value = env(name, str(default))
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    value = env(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


def env_int(name, default=0):
    value = env(name, str(default))
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', 'django-insecure-local-development-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')

SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', False)
SECURE_HSTS_SECONDS = env_int('SECURE_HSTS_SECONDS', 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', False)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', False)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Header di sicurezza aggiuntivi (utili per Lighthouse "Best Practices")
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'SAMEORIGIN'

SITE_URL = env('SITE_URL', 'https://polisportivasanmarinese.it')  # usato per condivisione social e meta SEO
SITE_NAME = 'Polisportiva Sanmarinese'
SITE_DESCRIPTION = (
    'Polisportiva Sanmarinese ASD-APS: scuola di ciclismo, squadra agonistica, '
    'eventi e attività sociali a San Marino di Carpi.'
)
GOOGLE_ANALYTICS_ID = env('GOOGLE_ANALYTICS_ID')
GOOGLE_SITE_VERIFICATION = env('GOOGLE_SITE_VERIFICATION')
FACEBOOK_PAGE_ID = env('FACEBOOK_PAGE_ID', '100057579972656')

DEFAULT_GOOGLE_CALENDAR_ICS_URL = (
    'https://calendar.google.com/calendar/ical/'
    'polisportivasanmarinese%40gmail.com/public/basic.ics'
)
GOOGLE_CALENDAR_ICS_URL = env('GOOGLE_CALENDAR_ICS_URL', DEFAULT_GOOGLE_CALENDAR_ICS_URL)
if not GOOGLE_CALENDAR_ICS_URL or '...' in GOOGLE_CALENDAR_ICS_URL:
    GOOGLE_CALENDAR_ICS_URL = DEFAULT_GOOGLE_CALENDAR_ICS_URL


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'ckeditor',
    'home',
    'news',
    'events',
    'sponsors',
    'documents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise subito dopo SecurityMiddleware per servire static
    # con gzip/brotli e header di cache lunghi (Apache/Gunicorn).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # GZip come fallback se whitenoise non copre una risposta.
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
]

# Cache per-site: pagine anonime per 5 minuti in RAM locale.
# In produzione con più worker Gunicorn considerare Redis.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'polisportiva-default',
    }
}
CACHE_MIDDLEWARE_SECONDS = env_int('CACHE_MIDDLEWARE_SECONDS', 300)
CACHE_MIDDLEWARE_KEY_PREFIX = 'polisp'
CACHE_MIDDLEWARE_ALIAS = 'default'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.analytics',
                'home.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if env('DATABASE_ENGINE') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('POSTGRES_DB'),
            'USER': env('POSTGRES_USER'),
            'PASSWORD': env('POSTGRES_PASSWORD'),
            'HOST': env('POSTGRES_HOST', 'localhost'),
            'PORT': env('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise + Manifest storage:
# - collectstatic rinomina i file con hash (style.abc123.css)
# - Precomprime in .gz e .br (brotli) grazie a whitenoise[brotli]
# - Serve con Cache-Control: max-age=1 year, immutable
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

WHITENOISE_MAX_AGE = 60 * 60 * 24 * 365  # 1 anno sui file con hash
WHITENOISE_USE_FINDERS = DEBUG  # in dev trova anche quelli non ancora collectati

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email
# In sviluppo: stampa le email sul terminale
# In produzione: sostituire con smtp.gmail.com e le credenziali reali
EMAIL_BACKEND = env('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')        # es. polisportiva@gmail.com
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')    # App Password Gmail

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', 'noreply@polisportivasanmarinese.it')
CONTACT_EMAIL = env('CONTACT_EMAIL', 'polisportivasanmarinese@gmail.com')

# Primary key default type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 420,
        'width': '100%',
        'language': 'it',
        'allowedContent': True,
    },
}

# PayPal — inserisci i valori nel file .env
# Credenziali: https://developer.paypal.com/
PAYPAL_MODE = env('PAYPAL_MODE', 'sandbox')       # 'sandbox' oppure 'live' in produzione
PAYPAL_CLIENT_ID = env('PAYPAL_CLIENT_ID')
